#!/bin/bash
#
# kubectl plugin script for stml.
# To install this script run the commands:
#  
#    stml --kubectl | sudo tee /usr/local/bin/kubectl-stml
#    sudo chmod +x /usr/local/bin/kubectl-stml
#

TEMP_FOLDER=".stml"

function help() {
    VERSION=$(stml --version | cut -c 6-)
    echo "kubectl STML plugin $VERSION"
    echo ""
    echo "The plugin is a STML compiler integration with kubectl to be able"
    echo "remove extra steps from the work flow."
    echo ""
    echo "Apply:"
    echo "The integation for the apply subcommand is doing an extra compilation step of "
    echo "STML files into $TEMP_FOLDER. The results are then passed to kubctl apply"
    echo ""
    echo "Options:"
    echo "  -f FILE     Compiles a STML file to YAML."
    echo "  -d DIR      Compiles all STML files in a directory to YAML."
    echo ""
    echo "All other options are passed straight to kubectl apply"
    echo ""
}

if [ -z "$1" ]; then
    help   
    exit 1 
fi


if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]] ; then
    help
    exit 0    
fi

if [ "$1" == "apply" ]; then
    FILE=""
    DIR=""
    ARGS=""

    shift
    while [[ $# -gt 0 ]]
    do
        case "$1" in
            -h|--help)
            help
            exit 0            
            ;;
            -f)
            FILE="$2"
            shift
            shift
            ;;
            -d)
            DIR="$2"
            shift
            shift
            ;;
            *)
            ARGS="$ARGS $1"
            shift
            ;;
        esac
    done

    if [ ! -d "$TEMP_FOLDER" ]; then
        mkdir -p "$TEMP_FOLDER"
    fi

    if [ ! -z "$FILE" ]; then
        echo "COMPILING STML:"
        FILENAME=$(basename "$FILE")
        OUTPUT="$TEMP_FOLDER/$FILENAME"        
        echo "  $FILE"
        stml -o "$OUTPUT" $FILE
        kubectl apply -f $OUTPUT $ARGS
    elif [ ! -z "$DIR" ]; then
        if [ -d "$TEMP_FOLDER" ]; then
            rm "./$TEMP_FOLDER/*"
        fi

        echo "COMPILING STML:"
        for file in $(ls -1 "$DIR" | grep ".stml$")
        do
            FILENAME=$(basename "$file")
            OUTPUT="$TEMP_FOLDER/$FILENAME"        
            echo "  $FILENAME"
            stml -o "$OUTPUT" "$DIR/$file"
        done
        echo kubectl apply -d $TEMP_FOLDER $ARGS
    else
        echo "ERROR: None of the required flags -f and -d were specied!"
        echo ""
        help 
        exit 1
    fi   
fi


echo "ERROR: Unrecognized command: $1"
exit 1
