#!/bin/bash
#
# kubectl plugin script for stml.
# To install this script run the commands:
#  
#    stml --kubectl | sudo tee /usr/local/bin/kubectl-stml
#    sudo chmod +x /usr/local/bin/kubectl-stml
#

TEMP_FOLDER=".stml"

function help() {
    VERSION=$(stml --version | cut -c 6-)
    echo "kubectl STML plugin $VERSION"
    echo ""
    echo "The plugin is a STML compiler integration with kubectl to be able"
    echo "remove extra steps from the work flow."
    echo ""
    echo "Apply:"
    echo "The integation for the apply subcommand is doing an extra compilation step of "
    echo "STML files into $TEMP_FOLDER. The results are then passed to kubctl apply"
    echo ""
    echo "Options:"
    echo "  -f FILE     Compiles a STML file to YAML."
    echo "  -k DIR      Compiles all STML files in a directory to YAML."
    echo ""
    echo "All other options are passed straight to kubectl apply"
    echo ""
    echo "Installation:"
    echo "Install the plugin by copying it to the path with the name \"kubectl-stml\""
    echo ""
    echo "    stml generate-kubectl | sudo tee /usr/local/bin/kubectl-stml"
    echo "    sudo chmod +x /usr/local/bin/kubectl-stml"
    echo ""
}

if [ -z "$1" ]; then
    help   
    exit 1 
fi


if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]] ; then
    help
    exit 0    
fi

if [ "$1" == "apply" ]; then
    FILE=""
    DIR=""
    ARGS=""

    shift
    while [[ $# -gt 0 ]]
    do
        case "$1" in
            -h|--help)
            help
            exit 0            
            ;;
            -f)
            FILE="$FILE $2"
            shift
            shift
            ;;
            -k)
            DIR="$2"
            shift
            shift
            ;;
            *)
            ARGS="$ARGS $1"
            shift
            ;;
        esac
    done

    if [ ! -d "$TEMP_FOLDER" ]; then
        mkdir -p "$TEMP_FOLDER"
    fi

    if [ -n "$FILE" ]; then
        FILENAME=$(basename "$FILE")
        OUTPUT="$TEMP_FOLDER/$FILENAME"        
        echo "compiling $FILE"
        stml compile "$FILE" -o "$OUTPUT"
        kubectl apply -f "$OUTPUT" $ARGS
        exit $?
    elif [ -n "$DIR" ]; then
        if [ -d "$TEMP_FOLDER" ]; then
            rm -rf "./$TEMP_FOLDER"
            mkdir $TEMP_FOLDER
        fi

        DIR=$(readlink -f $DIR)
        FILES=$(ls $DIR/*.stml)

        stml compile "$FILES" -o "$TEMP_FOLDER"
        kubectl apply -k "$TEMP_FOLDER" $ARGS
        exit $?
    else
        echo "ERROR: None of the required flags -f and -d were specified!"
        echo ""
        help 
        exit 1
    fi   
fi

echo "ERROR: Unrecognized command: $1"
exit 1

#
# Install using:
#
#    stml generate-kubectl | sudo tee /usr/local/bin/kubectl-stml
#    sudo chmod +x /usr/local/bin/kubectl-stml
#